Repository laminas/laminas-crypt, pull requests merged in 2021-11, with the labels that each got.

#15 Added support for PHP 8.1
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Hybrid.php
  src/Key/Derivation/SaltedS2k.php
  src/Symmetric/Openssl.php
  test/FileCipher/AbstractFileCipherTest.php
Labels: Enhancement

#16 Removes outdated content from index page
  README.md
Labels: Documentation, Enhancement

#17 Adds the content for the readme file back
  README.md
Labels: Bug, Documentation
